### ISSUE TITLE
about external smtp public server

### ISSUE THREAD

**Issue by chisNaN** [tophfr/docker-mailhog#1]
Hello tophfr

I saw you are french native speaking (as i) but may write in english if someone else may read my question.

I am currently working on myself making a docker compose webstack comprising:
-php7 apache, nginx proxy, phpmyadmin, mysql latest, redis, rabbitmq, mailhog

I can "catch" email from php with mailhog but now i would like to send them for REAL
and was wondering if by changing these values in the docker-compose you made:

`MH-OUTGOING_CONTENT: '{ "mysmtp": { "name": "MySMTP", "host": "smtp.gmail.com", "port": "587", "email": "my_email_address@gmail.com:password" } }'

would work to send emails?
Is the combination for email password syntax possible?

I tried directly on your docker compose project but without success(((

I would like to avoid to resort to a smtp server installed on the host machine...

Merci d'avance

**Comment by tophfr** [comment]
Bonjour chisNaN

First thank you, you made me realize that `MH_OUTGOING_CONTENT` is misspelled in the comment line of my `docker-compose.yml`.

That var is just my way of using the [Outgoing SMTP configuration](https://github.com/mailhog/MailHog/blob/master/docs/CONFIG.md#outgoing-smtp-configuration) option of Mailhog without a file.
As you can see in the documentation there is a `password` field that should meet your needs.

I'm not sure I understood precisely what you want to do, but this option allow you to release a message to the outside world only manually from the UI.
I do think there's a way of auto-releasing every messages. In fact that's not the point of that tool.
If you want to send email directly, why would you want to use Mailhog for ?

BR

**Comment by chisNaN** [comment]
Thanks for your reply!

I did not realise mailhog is made to catch AND then PAUSE the emails from server script.
I dont event know where is the option to send the email for real in the interface (if I understood what you say).
I thought mailhog was an interface to "keep a trace" of emails and real sending was automatically done...
Shame on me! I just see now the small button saying to "release the message" and inviting typing SMTP values

**Comment by tophfr** [comment]
It's an email catcher tool for testing purposes.
Very useful in a development or staging environment.
